apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:multicluster-global-hub-apiserver
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["policies", "placementbindings"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
- apiGroups: ["apps.open-cluster-management.io"]
  resources: ["placementrules"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["get", "create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["get", "create"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters", "hubcontrolplanes"]
  verbs: ["create", "get", "list", "watch", "patch", "delete"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters/status", "hubcontrolplanes/status"]
  verbs: ["patch", "update"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["policies/status"]
  verbs: ["update", "patch"]