apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: multicluster-global-hub-apiserver
  namespace: open-cluster-management
spec:
  port:
    targetPort: secure
  tls:
    termination: passthrough
  to:
    kind: Service
    name: multicluster-global-hub-apiserver
    weight: 100
  wildcardPolicy: None