FROM quay.io/bitnami/golang:1.17 AS builder
WORKDIR /go/src/github.com/clyang82/hohapiserver
COPY . .

RUN make build --warn-undefined-variables

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
ENV USER_UID=10001

COPY --from=builder /go/src/github.com/clyang82/hohapiserver/hohsyncer /
RUN microdnf update && microdnf clean all

USER ${USER_UID}