apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:multicluster-global-hub-syncer
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy.open-cluster-management.io"]
  resources: ["policies", "placementbindings", "policies/status"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters", "managedclusters/status", "hubcontrolplanes"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]
- apiGroups: ["apps.open-cluster-management.io"]
  resources: ["placementrules"]
  verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get"]
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["clustermanagementaddons"]
  verbs: ["get", "list", "watch"]